
---

## 🚀 Topics Covered
1. **Basic Web UI Testing** – Writing and running automated test cases for login and form validation.
2. **Page Object Model (POM)** – Organizing locators and actions in reusable classes.
3. **UI Assertions** – Verifying element visibility, text content, and URL changes.
4. **API Assertions** – Testing API responses directly in Playwright.
5. **CI/CD Integration** – Running tests automatically in GitHub Actions.
6. **Automated Test Reports** – Generating HTML and JUnit reports after execution.

---

## 🛠 Tools & Technologies
- [Playwright](https://playwright.dev/)
- Node.js
- GitHub Actions (CI/CD)
- Postman & Thunder Client
- VSCode
- GitHub Desktop

---

## 📸 Sample Test Execution
![Test Report Screenshot](docs/assets/test-report-login.png)

---

## 📬 Contact
**Gagas Langgeng Dwi Prastyo**  
📧 Email: gagasldp99@gmail.com  
🔗 LinkedIn: [Gagas Langgeng Dwi Prastyo](https://www.linkedin.com/in/gagas-langgeng-dwi-prastyo-953713238/)  
📂 Portfolio: [Playwright Automation Portfolio](https://github.com/Gagasldp/playwright-automation-portfolio.git)
